### ISSUE TITLE
Only log informations for commands of interest

### ISSUE THREAD

**Issue by gjeusel** [tiangolo/poetry-version-plugin#12]
Hey there ! Thx for this plugin

Would it be possible to silence the messages ?
It's a bit annoying when using poetry commands unrelated to the versioning:

```bash
> poetry env list
poetry-version-plugin: Using __init__.py file at pylsp_mypy_rnx/__init__.py for dynamic version
poetry-version-plugin: Setting package dynamic version to __version__ variable from __init__.py: 0.1.0
pylsp-mypy-rnx-Thao6M6B-py3.9 (Activated)
```

**Comment by thosil** [comment]
Indeed it would be very nice to either use a verbosity level, or send output to stderr.

Especially for commands like `poetry version -s`

**Comment by tiangolo** [comment]
Thanks for the patience with my reply! :sweat_smile: 

I just marked this project as deprecated, I'm currently not using it and I think these ideas can be achieved in better ways: https://github.com/tiangolo/poetry-version-plugin#-warning-deprecated-

Given that I'll close this one, but thanks for the interest! :coffee:
