### ISSUE TITLE
Consider using Dunamai for Git and other version control systems

### ISSUE THREAD

**Issue by mtkennerly** [tiangolo/poetry-version-plugin#14]
Hi! I found your project while looking through some Poetry issues, and I just wanted to suggest possibly using [Dunamai](https://pypi.org/project/dunamai/) for the Git integration. Disclosure: I wrote it for use in [another versioning plugin](https://github.com/mtkennerly/poetry-dynamic-versioning), but I think it would be useful for yours too. It takes care of a lot of annoying edge cases, and it supports other VCSes as well (Mercurial, Darcs, Subversion, Bazaar, and Fossil).

**Comment by sl304227-nh** [comment]
Do we think it would be easier to refactor `poetry-dynamic-versioning` to use plugins, or refactor `poetry-version-plugin` to add the Dunamai?

Proceeding forward with 1 package/plugin seems to make more sense for poetry.  I'm loving both @mtkennerly and @tiangolo packages so far.

**Comment by tiangolo** [comment]
Thanks for the patience with my reply! :sweat_smile: 

I just marked this project as deprecated with some alternative suggestions: https://github.com/tiangolo/poetry-version-plugin#-warning-deprecated-

Given that I'll close this one, but thanks for the interest! :coffee:
