### ISSUE TITLE
Commit hash fallback in absence of tag

### ISSUE THREAD

**Issue by qwenger** [tiangolo/poetry-version-plugin#17]
Hi,

Thanks for this plugin!

I am aware that this plugin is kind of temporary and may end up merged with `poetry-dynamic-versioning` (or even built into poetry directly?), so adding all kind of functionality may be premature.

Still a suggestion: it could be useful to be able to use the commit short hash when no tag is set for the current commit, e.g. as a "git-tag-or-commit" option. Maybe something along these lines: https://gist.github.com/mjj2000/3ee188cc155c26a118b06116ad0ebd1d

**Comment by caniko** [comment]
@tiangolo ?

**Comment by tiangolo** [comment]
Thanks for the patience with my reply! :sweat_smile: 

I just marked this project as deprecated, I'm currently not using it and I think these ideas can be achieved in better ways: https://github.com/tiangolo/poetry-version-plugin#-warning-deprecated-

Given that I'll close this one, but thanks for the interest! :coffee:
