### ISSUE TITLE
`__init__.py` detection does not assume the existence of `from` specification of packages 

### ISSUE THREAD

**Issue by TatsuyaShirakawa** [tiangolo/poetry-version-plugin#19]
If the project is organized like

```
root
   |- src
   |     |- my_package
   |- pyproject.toml
```

and `pyproject.toml` is like

```
[tool.poetry]
...
packages = [
    { include = "my_package" from = "src" }
]
...
[tool.poetry-version-plugin]
source = "init"
```

then, the detection of `__init__.py` fails.

It is because, I think, the `__init__.py` detection logic [here](https://github.com/tiangolo/poetry-version-plugin/blob/89f9aaf02cbdc6a2a5972c07b167e78314ad153b/poetry_version_plugin/plugin.py#L42) does not consider the `from` value.

**Comment by jessekrubin** [comment]
Same for me.

**Comment by dekoza** [comment]
Fixed with #20 :slightly_smiling_face:

**Comment by setu4993** [comment]
@tiangolo : If possible for you, would be great to incorporate PR https://github.com/tiangolo/poetry-version-plugin/pull/20. I'd love to use this plugin but because I use the `src` structure, the current release version doesn't work for me :/.

**Comment by tiangolo** [comment]
Thanks for the patience with my reply! :sweat_smile: 

I just marked this project as deprecated, I'm currently not using it and I think these ideas can be achieved in better ways: https://github.com/tiangolo/poetry-version-plugin#-warning-deprecated-

Given that I'll close this one, but thanks for the interest! :coffee:
