### ISSUE TITLE
[ENH] Refactoring nested if structure

### ISSUE THREAD

**Issue by Anselmoo** [tiangolo/poetry-version-plugin#21]
**Thx for the plugin!**

Some of the `if-if` statements can be summarized via `if + and`

Maybe that's something to consider

https://github.com/tiangolo/poetry-version-plugin/blob/89f9aaf02cbdc6a2a5972c07b167e78314ad153b/poetry_version_plugin/plugin.py#L57-L77

**Comment by tiangolo** [comment]
Thanks for the patience with my reply! :sweat_smile: 

I just marked this project as deprecated, I'm currently not using it and I think these ideas can be achieved in better ways: https://github.com/tiangolo/poetry-version-plugin#-warning-deprecated-

Given that I'll close this one, but thanks for the interest! :coffee:
