### ISSUE TITLE
Can it also tell me the git ref?

### ISSUE THREAD

**Issue by MatrixManAtYrService** [tiangolo/poetry-version-plugin#24]
Hi.  Thanks for poetry-version-plugin, I've found it really easy to use.  Now I can do:

```
$ mycliapp --version
mycliapp 1.2.3dev4
```

Sometimes I forget to add a tag, and an untagged version ends up in a co-worker's hands.  When this happens it's hard to be sure which version they actually have.  I'd like to be able to do this instead:

```
$ mycliapp --version
mycliapp 1.2.3dev4 
88f9aaf02cbdc6a2a5972c07b167e78314ad153b
```

Where `88f...3b` is the current git ref (not the ref of the tag, which might be i the past).  Is this information available?

**Comment by tiangolo** [comment]
Thanks for the patience with my reply! :sweat_smile: 

I just marked this project as deprecated, I'm currently not using it and I think these ideas can be achieved in better ways: https://github.com/tiangolo/poetry-version-plugin#-warning-deprecated-

Given that I'll close this one, but thanks for the interest! :coffee:
