### ISSUE TITLE
Plugin fails under Poetry 1.2.0rc2

### ISSUE THREAD

**Issue by mbeacom** [tiangolo/poetry-version-plugin#27]
This plugin currently fails using the latest RC of Poetry (`1.2.0rc2`).
There have been numerous changes to the Poetry core (to include movement and removal of some methods).

If you attempt to run poetry commands following installation of this plugin under rc2, you will encounter a `module_name` not found in `poetry.utils.helpers@module_name` (as it is no longer available here, but rather: `poetry.core.utils.helpers@module_name`
Additionally, `set_version` was removed in a previous release (documented here):  https://github.com/python-poetry/poetry/issues/6223

This required the addition of `ProjectPackage._set_version` as discussed here: https://github.com/python-poetry/website/pull/70#issuecomment-1229139312

**Comment by tiangolo** [comment]
Thanks! And thanks for the fix! 🙇 

This was solved in https://github.com/tiangolo/poetry-version-plugin/pull/28, just released in version 0.2.0 🎉

**Comment by mbeacom** [comment]
Thanks for the merge!  Glad it helped.
