### ISSUE TITLE
Adding this plugin fails with: `The command "plugin" does not exist.`

### ISSUE THREAD

**Issue by maxnoe** [tiangolo/poetry-version-plugin#29]
Following the instructions in the README with poetry 1.3.2 fails with the following error:

```
❯ poetry plugin add poetry-version-plugin

The command "plugin" does not exist.

Did you mean this?
    self show plugins
```

Trying to install with the documented method in the poetry docs instead gives this error:
```
❯ poetry self add poetry-version-plugin

Invalid version '1.1build1' on package distro-info
```

**Comment by tiangolo** [comment]
Could you try with the latest version 0.2.0 just released?

**Comment by deronnax** [comment]
@tiangolo the command to add plugin to poetry seems to be `poetry self add poetry-version-plugin`. I confirm that `poetry plugin add poetry-version-plugin` showned in the README gives `The command "plugin" does not exist.`

**Comment by tiangolo** [comment]
Thanks! I just updated it in the README. 🤓

**Comment by deronnax** [comment]
(done in #31)
let's close this issue then :)
