### ISSUE TITLE
Problem adding new packages on poetry 1.5

### ISSUE THREAD

**Issue by JeyDi** [tiangolo/poetry-version-plugin#30]
Hi all!

I have a problem with the plugin, after the installation, if I launch `poetry add <newpackage>` the package will be installed but the `pyproject.toml` will not register the change in the file.

Also If I launched another package installation with `poetry add <second_new_package` poetry remove the old `<newpackage>` with all the dependencies.

I think this problem it's related to some pyproject configuration in the plugin, like this open issue in Poetry project: https://github.com/python-poetry/poetry/issues/7230

- Poetry version: Poetry (version 1.5.1)
- Python version: Python: 3.9.16
- OS version and name: macOS 13.4.1 ARM

Has anyone experienced the same problem?

**Comment by tiangolo** [comment]
Thanks for the patience with my reply! :sweat_smile: 

I just marked this project as deprecated, I'm currently not using it and I think these ideas can be achieved in better ways: https://github.com/tiangolo/poetry-version-plugin#-warning-deprecated-

Given that I'll close this one, but thanks for the interest! :coffee:
