### ISSUE TITLE
Don't complain when running poetry in a non git repo

### ISSUE THREAD

**Issue by davidolrik** [tiangolo/poetry-version-plugin#33]
When ever I run poetry in a non git repo I get the following error:

```
poetry-git-version-plugin: ValueError: Reference at 'refs/heads/main' does not exist. Ignore Exception.
```

As it is not a git repo, the plugin should not kick in, an this not show any errors.

**Comment by tiangolo** [comment]
Thanks for the patience with my reply! :sweat_smile: 

I just marked this project as deprecated, I'm currently not using it and I think these ideas can be achieved in better ways: https://github.com/tiangolo/poetry-version-plugin#-warning-deprecated-

Given that I'll close this one, but thanks for the interest! :coffee:
