### ISSUE TITLE
Git Tag Pattern Match

### ISSUE THREAD

**Issue by jacksonwb** [tiangolo/poetry-version-plugin#46]
Support for Git tags that match a pattern similar to PDM.
https://backend.pdm-project.org/metadata/#dynamic-project-version

Perhaps similar to #10

**Comment by tiangolo** [comment]
Thanks for the patience with my reply! :sweat_smile: 

I just marked this project as deprecated, I'm currently not using it and I think these ideas can be achieved in better ways: https://github.com/tiangolo/poetry-version-plugin#-warning-deprecated-

Given that I'll close this one, but thanks for the interest! :coffee:
