### ISSUE TITLE
Only log to stdout on -vv?

### ISSUE THREAD

**Issue by raayu83** [tiangolo/poetry-version-plugin#48]
Currently the plugin always logs what it does, even when you call `poetry version --short`.
This means you can't use the result of `poetry version --short` as an argument for other commands directly.
I'd suggest to output to the Log only when verbosity is set to `-vv` or higher.

**Comment by tiangolo** [comment]
Thanks for the patience with my reply! :sweat_smile: 

I just marked this project as deprecated, I'm currently not using it and I think these ideas can be achieved in better ways: https://github.com/tiangolo/poetry-version-plugin#-warning-deprecated-

Given that I'll close this one, but thanks for the interest! :coffee:
