### ISSUE TITLE
Update the version resource when using poetry version

### ISSUE THREAD

**Issue by aviramha** [tiangolo/poetry-version-plugin#7]
Hi! 
Thanks for the plugin. It can solve real inconsistencies when using poetry for packages.
I think you should consider adding support for altering the version using the `poetry version minor/patch/major`.
I don't mind sending a PR if you see this suggestion fitting.

**Comment by tiangolo** [comment]
Yes, I would definitely accept a PR with that. 🚀 

I'm not sure if it's possible with the current plugin system in Poetry, and I'm also not sure about how to write code from the AST with the new version, but if all that's possible, that would be great indeed.
